#When true, you unlock all skills by default. If toggled halfway through a world, your unlocked skills will become locked and vice versa. Recommended for experienced players only.
"Grandmaster Mode" = false

